-- T023: V3__seed_payment_descriptions.sql
-- Seeds payment_descriptions with codes 1–89.
-- In production, codes 90–99 are fetched dynamically from MUTF08 via MemberPort.

INSERT INTO payment_descriptions (code, description_nl, description_fr, description_de) VALUES
(1,  'Bijdrage terugbetaling',            'Remboursement cotisation',            'Beitrag Rückzahlung'),
(2,  'Hospitalisatiekosten',              'Frais d''hospitalisation',            'Krankenhauskosten'),
(3,  'Geneeskundige kosten',              'Frais médicaux',                      'Ärztliche Kosten'),
(4,  'Tandheelkundige kosten',            'Frais dentaires',                     'Zahnarztkosten'),
(5,  'Verloskundige kosten',              'Frais d''accouchement',               'Geburtskosten'),
(6,  'Opticienkosten',                    'Frais d''opticien',                   'Optikerkosten'),
(7,  'Paramedische kosten',               'Frais paramédicaux',                  'Paramedizinische Kosten'),
(8,  'Geneesmiddelen',                    'Médicaments',                         'Medikamente'),
(9,  'Hulpmiddelen',                      'Aides techniques',                    'Hilfsmittel'),
(10, 'Revalidatiekosten',                 'Frais de rééducation',                'Rehabilitationskosten'),
(11, 'Kinesitherapie',                    'Kinésithérapie',                      'Physiotherapie'),
(12, 'Logopedie',                         'Logopédie',                           'Logopädie'),
(13, 'Ergotherapie',                      'Ergothérapie',                        'Ergotherapie'),
(14, 'Verpleegkosten thuis',              'Soins infirmiers à domicile',         'Pflegekosten zu Hause'),
(15, 'Rolstoel en aanpassingen',          'Fauteuil roulant et adaptations',     'Rollstuhl und Anpassungen'),
(16, 'Prothesen en orthesen',             'Prothèses et orthèses',               'Prothesen und Orthesen'),
(17, 'Transport zieke',                   'Transport du malade',                 'Krankentransport'),
(18, 'Begrafenisvergoeding',              'Allocation funéraire',                'Beerdigungszuschuss'),
(19, 'Invaliditeitsvergoeding',           'Allocation d''invalidité',            'Invaliditätszuschuss'),
(20, 'Arbeidsongeschiktheid',             'Incapacité de travail',               'Arbeitsunfähigkeit'),
(21, 'Moederschapsvergoeding',            'Allocation de maternité',             'Mutterschaftszuschuss'),
(22, 'Adoptie-uitkering',                 'Allocation d''adoption',              'Adoptionsleistung'),
(23, 'Vaderschapsverlof',                 'Congé de paternité',                  'Vaterschaftsurlaub'),
(24, 'Mantelzorgvergoeding',              'Allocation aidant proche',            'Pflegezuschuss'),
(25, 'Palliatief verlof',                 'Congé palliatif',                     'Palliativurlaub'),
(26, 'Medex-vergoeding',                  'Allocation Medex',                    'Medex-Zulage'),
(27, 'Bijstand chronisch zieken',         'Aide malades chroniques',             'Chronisch Kranken Hilfe'),
(28, 'Kankerfonds vergoeding',            'Allocation fonds cancer',             'Krebsfonds Zulage'),
(29, 'Terugbetaling supplement',          'Remboursement supplément',            'Zusatzbetrag Erstattung'),
(30, 'Bijkomend legalisatiekosten',       'Frais légalisation supplémentaires',  'Zusätzliche Legalisierungskosten'),
(31, 'Buitenlandse behandeling',          'Traitement à l''étranger',            'Auslandsbehandlung'),
(32, 'Preventieve geneeskunde',           'Médecine préventive',                 'Präventivmedizin'),
(33, 'Geestelijke gezondheidszorg',       'Soins santé mentale',                 'Psychische Gesundheitsversorgung'),
(34, 'Dagopvang gehandicapten',           'Accueil de jour handicapés',          'Tagesbetreuung Behinderter'),
(35, 'Nachtopvang gehandicapten',         'Accueil de nuit handicapés',          'Nachtbetreuung Behinderter'),
(36, 'Residentiële opvang',               'Accueil résidentiel',                 'Stationäre Betreuung'),
(37, 'Woonzorgcentrum',                   'Maison de repos et soins',            'Pflegeheim'),
(38, 'Serviceflat',                       'Appartement de service',              'Servicewohnung'),
(39, 'Kortverblijf',                      'Court séjour',                        'Kurzzeitaufenthalt'),
(40, 'Dagverzorging',                     'Soins de jour',                       'Tagespflege'),
(41, 'Psychiatrische opname',             'Hospitalisation psychiatrique',        'Psychiatrischer Aufenthalt'),
(42, 'Crisisopvang',                      'Accueil de crise',                    'Krisenaufnahme'),
(43, 'Begeleiding jongeren',              'Accompagnement jeunes',               'Jugendbegleitung'),
(44, 'Gezinsbegeleiding',                 'Accompagnement familial',             'Familienbegleitung'),
(45, 'Schuldhulpverlening',               'Aide gestion dettes',                 'Schuldenberatung'),
(46, 'Sociale integratie',                'Intégration sociale',                 'Soziale Integration'),
(47, 'Beroepsopleidingskosten',           'Frais formation professionnelle',     'Berufsausbildungskosten'),
(48, 'Alfabetiseringscursus',             'Cours alphabétisation',               'Alphabetisierungskurs'),
(49, 'Taallessen',                        'Cours de langue',                     'Sprachkurs'),
(50, 'Sportactiviteiten',                 'Activités sportives',                 'Sportaktivitäten'),
(51, 'Culturele activiteiten',            'Activités culturelles',               'Kulturaktivitäten'),
(52, 'Vakantieregeling',                  'Réglementation vacances',             'Urlaubsregelung'),
(53, 'Jeugdkamp',                         'Camp de jeunesse',                    'Jugendlager'),
(54, 'Ouderenzorg',                       'Soins personnes âgées',               'Seniorenpflege'),
(55, 'Daguitstap senioren',               'Excursion seniors',                   'Seniorenausflug'),
(56, 'Inkomensgarantie ouderen',          'Garantie revenu personnes âgées',     'Einkommensgarantie Ältere'),
(57, 'Groeipakket',                       'Paquet croissance',                   'Wachstumspaket'),
(58, 'Studiefinanciering',                'Financement études',                  'Studienfinanzierung'),
(59, 'Schoolpremie',                      'Prime scolaire',                      'Schulprämie'),
(60, 'Schoolmateriaal',                   'Matériel scolaire',                   'Schulmaterial'),
(61, 'Kinderopvang',                      'Garde d''enfants',                    'Kinderbetreuung'),
(62, 'Buitenschoolse opvang',             'Accueil extrascolaire',               'Außerschulische Betreuung'),
(63, 'Vakantiekinderopvang',              'Garde vacances scolaires',            'Ferienkinderbetreuung'),
(64, 'Adoptiekosten',                     'Frais d''adoption',                   'Adoptionskosten'),
(65, 'Pleegzorgvergoeding',               'Allocation accueil familial',         'Pflegezulage'),
(66, 'Wezenbijdrage',                     'Allocation orphelin',                 'Waisenzuschuss'),
(67, 'Overlevingspensioen',               'Pension de survie',                   'Hinterbliebenenpension'),
(68, 'Rustpensioen',                      'Pension de retraite',                 'Ruhepension'),
(69, 'Aanvullend pensioen',               'Pension complémentaire',              'Zusatzpension'),
(70, 'Vakantiegeld',                      'Pécule de vacances',                  'Urlaubsgeld'),
(71, 'Eindejaarspremie',                  'Prime de fin d''année',               'Jahresendzuschlag'),
(72, 'Getrouwheidsbonus',                 'Bonus de fidélité',                   'Treueprämie'),
(73, 'Syndicale premie',                  'Prime syndicale',                     'Gewerkschaftsprämie'),
(74, 'Staking uitkering',                 'Allocation de grève',                 'Streikunterstützung'),
(75, 'Brugpensioen',                      'Prépension',                          'Vorruhestand'),
(76, 'Tijdskrediet',                      'Crédit-temps',                        'Zeitkredit'),
(77, 'Loopbaanonderbreking',              'Interruption de carrière',            'Berufsunterbrechung'),
(78, 'Deeltijds werken',                  'Travail à temps partiel',             'Teilzeitarbeit'),
(79, 'Economische werkloosheid',          'Chômage économique',                  'Wirtschaftliche Arbeitslosigkeit'),
(80, 'Inschakelingsuitkering',            'Allocation d''insertion',             'Eingliederungsleistung'),
(81, 'OCMW bijstand',                     'Aide CPAS',                           'ÖSHZ Unterstützung'),
(82, 'Leefloon',                          'Revenu d''intégration',               'Sozialhilfe'),
(83, 'Huurpremie',                        'Prime de loyer',                      'Mietprämie'),
(84, 'Huursubsidie',                      'Subvention de loyer',                 'Mietsubvention'),
(85, 'Verbouwingspremie',                 'Prime de rénovation',                 'Renovierungsprämie'),
(86, 'Energiepremie',                     'Prime énergie',                       'Energieprämie'),
(87, 'Verwarmingstoelage',                'Allocation chauffage',                'Heizungszuschuss'),
(88, 'Watertoelage',                      'Allocation eau',                      'Wasserzuschuss'),
(89, 'Diverse sociale uitkeringen',       'Diverses allocations sociales',       'Diverse Sozialleistungen');
