spring:
  datasource:
    url: jdbc:h2:mem:MYFIN;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration,classpath:db/dev
